apiVersion: v1
kind: Namespace
metadata:
  name: rhacs-operator
  annotations:
    openshift.io/node-selector: ""
    argocd.argoproj.io/sync-wave: "1"
  labels:
    openshift.io/cluster-monitoring: "true"
